### ISSUE TITLE
Crash call delegate [didCaptureVideoSampleBuffer]

### ISSUE THREAD

**Issue by remirobert** [piemonte/PBJVision#260] opened 2015-06-20 18:19 UTC
Hi, i got i crash with this delegate : 

I really need this call, this is essential for my application.
How can i fix it ?

```Objective-c
- (void)vision:(PBJVision *)vision didCaptureVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer;
```

Thanks in advance.

**Comment by olivierlesnicki** [comment] 2015-06-21 10:09
This is a duplicate of https://github.com/piemonte/PBJVision/issues/254

**Comment by remirobert** [comment] 2015-06-21 11:16
Ok thanks. So what is your solution. Because I didn't find the solution there. And I don't want modify the code. This is a major bug.

**Comment by piemonte** [comment] 2015-06-23 00:27
thanks for reporting, someone will take a look. yes, is a duplicate.

**Closed by piemonte** 2015-06-23 00:27 UTC
